// Baza de citate pentru Feed — filler zilnic (RO + INTL).
// Format: { text, author, origin: 'RO' | 'INTL' }
export const ALL_QUOTES = [
  { text: "Omul este o persoană umană.", author: "Gică Hagi", origin: "RO" },
  { text: "Eu când o spun chiar o zic.", author: "Gică Hagi", origin: "RO" },
  { text: "O să pățim cum a pățit ăla mai mic care îl cheamă mai mic.", author: "Gică Hagi", origin: "RO" },
  { text: "55 de jucători în 5 ani sunt 10 pe an.", author: "Gică Hagi", origin: "RO" },
  { text: "La anul vine un an nou și alt an.", author: "Gică Hagi", origin: "RO" },
  { text: "Un lider e un conducător, care te face când tu, unde stai tu, tuturor vă e mai bine.", author: "Gică Hagi", origin: "RO" },
  { text: "Vă dau iar o bombă... de judecată! Tac din gură că dacă o scot e bombă.", author: "Gică Hagi", origin: "RO" },
  { text: "În perioada de iarnă, jucătorii, când faci bine, poți să fii să ajungi să îți vină bine.", author: "Gică Hagi", origin: "RO" },
  { text: "H înseamnă harnic. A înseamnă ambiție. G înseamnă generos. I înseamnă iute.", author: "Gică Hagi", origin: "RO" },
  { text: "Nu are încă tempo, timpul, timingul, trăirea, spiritul acela care îți dă un meci întotdeauna.", author: "Gică Hagi", origin: "RO" },
  { text: "Copii, mergeți la școală, că și școala e bună la ceva!", author: "Gică Hagi", origin: "RO" },
  { text: "Important e punctele.", author: "Gică Hagi", origin: "RO" },
  { text: "Care e calitatea numărul 1 a latinului? Care e? Creativitatea, adică coco.", author: "Gică Hagi", origin: "RO" },
  { text: "Vezi o fată, te uiți la ea, o vezi, dar după aia? La ea trebuie să vezi ce este înăuntru.", author: "Gică Hagi", origin: "RO" },
  { text: "Chiar dacă particip, chiar dacă sunt, chiar dacă exist.", author: "Gică Hagi", origin: "RO" },
  { text: "Ele sunt, există, se discută, se pot fi.", author: "Gică Hagi", origin: "RO" },
  { text: "Noi, constănțenii, vara muncim și iarna hibernăm. Iarna hibernăm, ca ursul.", author: "Gică Hagi", origin: "RO" },
  { text: "Eu m-am născut cu Olanda și cu Ajax. Eu pe atunci aveam șase ani.", author: "Gică Hagi", origin: "RO" },
  { text: "E mai mare ca mine, are capul mai mare ca mine, mingea e mai mare ca mine.", author: "Gică Hagi", origin: "RO" },
  { text: "Muzică, muzică, la dans... suntem la discotecă.", author: "Gică Hagi", origin: "RO" },
  { text: "Să vii la fotbal, să vezi un stadion ca atare, să vezi lumea plină.", author: "Gică Hagi", origin: "RO" },
  { text: "Am fost singur, sunt singur și o să mă duc, sunt lider, și o să mă duc cu ale mele. Că sunt lider. Sunt că așa sunt eu, așa m-a făcut mama.", author: "Gică Hagi", origin: "RO" },
  { text: "Dom'le, sunt doi jucători... părerea mea normal că o echipă e făcută din mulți.", author: "Gică Hagi", origin: "RO" },
  { text: "Când joacă în mijloc, scrie, nu că desenează, scrie și desenează. Și tehnica... cu ea scrii.", author: "Gică Hagi", origin: "RO" },
  { text: "Nu spun coco, spun minte, ca să înțeleagă mintea... care stă bine la minte și la picioare... adică inside, mintea înseamnă tot ce ai tu înăuntru.", author: "Gică Hagi", origin: "RO" },
  { text: "Din când în când mai aud și ce se aude prin autocar, când vorbesc cu voce tare.", author: "Gică Hagi", origin: "RO" },
  { text: "Un meci care fiecare meci are istoria lui, adică momentele lui în care poate să îți meargă în favoarea ta în pozitiv sau în negativ.", author: "Gică Hagi", origin: "RO" },
  { text: "Nu există rege la fotbal, cu toate că dacă puneți ghilimelele, ok, sunt.", author: "Gică Hagi", origin: "RO" },
  { text: "Un rege nu stă în trening... Regele stă pe yacht, conduce, cravată, nu știu ce costume de general sau ce mai are.", author: "Gică Hagi", origin: "RO" },
  { text: "Dacă marcăm un gol la început, pe urmă putem să jucăm și la 0-0.", author: "Gigi Becali", origin: "RO" },
  { text: "Mitică Dragomir este același pentru toți și diferit pentru fiecare.", author: "Gigi Becali", origin: "RO" },
  { text: "Imnul Stelei va fi o melodie religioasă și o să cânt eu, că sunt talentat.", author: "Gigi Becali", origin: "RO" },
  { text: "Acum nu ne mai stă nimeni în cale. Ia uite la Pepe ce mușchi are!", author: "Gigi Becali", origin: "RO" },
  { text: "Globurile astea sunt controlate de securisto-comuniști.", author: "Gigi Becali", origin: "RO" },
  { text: "Becali e un brand. Eu la Avicola Iași pot să fac pui Gigi Becali.", author: "Gigi Becali", origin: "RO" },
  { text: "Eu sunt finanțator, nu sponsor. Sponsorii dau cadouri. Eu nu dau cadouri.", author: "Gigi Becali", origin: "RO" },
  { text: "Dumnezeu a făcut asta ca să merg eu în Anglia să-mi cumpăr cămăși.", author: "Gigi Becali", origin: "RO" },
  { text: "Eu sunt în silenzio stampa față de ziariști. Cu televiziunile vorbesc.", author: "Gigi Becali", origin: "RO" },
  { text: "M-a făcut oligofren, eu l-am făcut zdreanță, dar nu ne-am insultat.", author: "Gigi Becali", origin: "RO" },
  { text: "Da' cine e dom'ne Nichita Stănescu ăsta? A adus mai mulți bani decât mine în România?", author: "Gigi Becali", origin: "RO" },
  { text: "Stai picior peste picior? Mută-ți, bă, picioarele, că n-ai talent.", author: "Gigi Becali", origin: "RO" },
  { text: "Vali Badea este cu trei clase peste Inzaghi.", author: "Gigi Becali", origin: "RO" },
  { text: "M-am dat și pe mine afară. Nu sunt mulțumit cum am gestionat treburile la club în acest sezon.", author: "Gigi Becali", origin: "RO" },
  { text: "El se mai enerva, dar eu îi ziceam: «Ce-ai, mă, Michele? Fii calm, Michele!»", author: "Gigi Becali", origin: "RO" },
  { text: "Sunt prostul lumii! Cel mai mare idiot, eu sunt.", author: "Gigi Becali", origin: "RO" },
  { text: "O să vină maxim doi jucători: Chiricheș, Chipciu și încă unul.", author: "Gigi Becali", origin: "RO" },
  { text: "Maseuza am fredonat-o și eu, pentru că îmi place foarte tare.", author: "Gigi Becali", origin: "RO" },
  { text: "Dacă nu veneai să-ți ceri scuze, te luam la picioare. Stai liniștit, că nu te bătea nimeni.", author: "Gigi Becali", origin: "RO" },
  { text: "Eu muncesc 24 de ore pe zi, iar uneori chiar și noaptea.", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Putem câștiga, dragul meu, numai să și putem!", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Ajungem la baraj... la Vidraru.", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Cei mai mari oameni ai lumii au fost mici.", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Familia e sfântă, pe când patria... cum să vă spun, patria e sacră.", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Olăroiu e un antrenor foarte bun, dar vine un moment când trebuie să pleci de la locul faptei.", author: "Dumitru Dragomir", origin: "RO" },
  { text: "Canicula a mai făcut două victime? Sper ca poliția să-și facă datoria și s-o prindă!", author: "Claudiu Răducanu", origin: "RO" },
  { text: "Eu nu-mi propun să dau gol, care e în fața porții, s-o înscrie!", author: "Claudiu Răducanu", origin: "RO" },
  { text: "La bulanu' meu o să dau și gol dacă o să mă convoacă.", author: "Claudiu Răducanu", origin: "RO" },
  { text: "Filosofia este o transcedentală propedeutică pentru sufletul bântuit de moarte...", author: "Cornel Dinu", origin: "RO" },
  { text: "E muncitor, foarte muncitor, dar terenul de fotbal nu e șantier.", author: "Cornel Dinu", origin: "RO" },
  { text: "Te faultează? Păi du-te bă la șah! Du-te la șah!", author: "Ionuț Popa", origin: "RO" },
  { text: "Aștept un tricou al lui Gigi pe care să scrie D.T., director tehnic.", author: "Ionuț Popa", origin: "RO" },
  { text: "Sincer, mie nu-mi place să mă duc la Vaslui! Păi, la ultimul meci au venit cu un tablou de-al meu și scria «Popa prostu'».", author: "Ionuț Popa", origin: "RO" },
  { text: "Se bagă la fotbal... acum sper că nu o să se bage și la echipă. Ar fi culmea să îmi facă echipa.", author: "Ionuț Popa", origin: "RO" },
  { text: "Sunt modest, dar vă spun: eu sunt bun.", author: "Marius Șumudică", origin: "RO" },
  { text: "Păi, să vină să mă caute pe mine acuma Gigi Becali să-mi zică «bă, ia traista asta...» Ce să-i spun lui Săpunaru, că îmi dă cu traista în cap?", author: "Marius Șumudică", origin: "RO" },
  { text: "Să le dăm câte un plic de anticârcel.", author: "Marius Șumudică", origin: "RO" },
  { text: "Mă mai ia transpirația așa, mai schimb pijamaua... Sunt supărat, sunt foarte bucuros. Îmi fac bagajul și am plecat la Budapesta.", author: "Vasile Miriuță", origin: "RO" },
  { text: "Credeți că jucătorii ăștia sunt roboți? Sunt tauri comunali?", author: "Vasile Miriuță", origin: "RO" },
  { text: "M-am uitat un pic așa la meci, am văzut golurile, dar am avut un film bun... sper să găsesc un film bun.", author: "Vasile Miriuță", origin: "RO" },
  { text: "Îl felicit pe Falub... poftim? Pardon, Cluj.", author: "Vasile Miriuță", origin: "RO" },
  { text: "O să se spună că dacă ne bate Viitorul am stat «capră». Jucătorii mei nu se prostituează.", author: "Vasile Miriuță", origin: "RO" },
  { text: "Mi-e să nu răcesc, să fac vreo emenangită.", author: "Vasile Turcu", origin: "RO" },
  { text: "Dinu, Țălnar și Mulțescu formează un tandem excelent.", author: "Vasile Turcu", origin: "RO" },
  { text: "Ganea este în stare să infecteze și penicilina.", author: "Marian Iancu", origin: "RO" },
  { text: "În fotbal intri bou și ieși vacă!", author: "Marian Iancu", origin: "RO" },
  { text: "Voi fi tot mai critic la ceea ce spun Gigi Becali și prietena lui, Giovani.", author: "Marian Iancu", origin: "RO" },
  { text: "Am venit bou și am plecat vacă.", author: "Mihai Stoica", origin: "RO" },
  { text: "N-avea cum să-mi rupă Fane capu'. Am gât flexibil, sunt ca Inspectorul Gadget.", author: "Mihai Stoica", origin: "RO" },
  { text: "M-am sfătuit cu mine însumi.", author: "Nicolae Mitea", origin: "RO" },
  { text: "Sunt pesimist. Cred că putem învinge Olanda.", author: "Nicolae Mitea", origin: "RO" },
  { text: "Va fi un meci greu și dificil.", author: "Florin Tănase", origin: "RO" },
  { text: "Nu știu câte goluri ar trebui să marcăm ca s-o eliminăm pe Betis. Cât mai multe ar fi suficiente.", author: "Gabi Boștină", origin: "RO" },
  { text: "Pase scurte și pe sus, ai n-ai mingea, tragi la poartă.", author: "Gabi Stan", origin: "RO" },
  { text: "Suporterii noștri sunt 80% din București și 40% din provincie.", author: "Ionel Dănciulescu", origin: "RO" },
  { text: "Dacă nu primim vreun gol probabil meciul are altă față și nu o să primim nici al doilea gol.", author: "Ionel Ganea", origin: "RO" },
  { text: "Nu pot să spun că am plâns, dar mi-au dat lacrimile.", author: "Cosmin Moți", origin: "RO" },
  { text: "Eu prin presupuneri deduc.", author: "Gheorghe Ștefan", origin: "RO" },
  { text: "Nu mi-e frică, dar mă tem.", author: "Marin Condescu", origin: "RO" },
  { text: "Dedic golul lui Ionuț Badea, care a născut în această dimineață o fetiță.", author: "Alexandru Bălțoi", origin: "RO" },
  { text: "Mi-a picat Comuna din Paris. Am cerut alt subiect, că eu nu prea le am cu geografia.", author: "Rică Răducanu", origin: "RO" },
  { text: "E un p... de vacă uscat de vânt.", author: "Adrian Mititelu", origin: "RO" },
  { text: "Universitatea Craiova este singura echipă care poate sparge cvartetul Steaua–Dinamo–Rapid.", author: "Adrian Mititelu", origin: "RO" },
  { text: "Dacă scoatem primele 30 de minute, cred că puteam să câștigăm.", author: "Adi Ilie", origin: "RO" },
  { text: "Suporterii trebuie să fie al 14-lea jucător.", author: "Marius Lăcătuș", origin: "RO" },
  { text: "Cred că o să candidez la președinția României. Pe unde mergem facem lumea fericită, luăm câte 5-6 goluri, suntem iubiți și aplaudați.", author: "Marius Stan", origin: "RO" },
  { text: "Banii sunt scumpi în ziua de azi.", author: "Gino Iorgulescu", origin: "RO" },
  { text: "O luptă între ei este mai frumoasă decât lupta în unul.", author: "Miodrag Belodedici", origin: "RO" },
  { text: "Jucătorii trebuie să fie concentrați, să fie mentalizați.", author: "Cosmin Contra", origin: "RO" },
  { text: "Am fost puțin fraieri, cum să zic așa, cum mai așa.", author: "Răzvan Grădinaru", origin: "RO" },
  { text: "Sperăm să fie un pas ascendent către obiectivul nostru și acela de-a ne salva.", author: "Marian Cristescu", origin: "RO" },
  { text: "Sunt fotbaliști care cântă la pian, dar și cară pianul. Mihăescu, tu ești unul care cari.", author: "Flavius Stoican", origin: "RO" },
  { text: "E ca și cum ai găsi un câine șchiop și tu să-i mai dai un picior.", author: "Flavius Stoican", origin: "RO" },
  { text: "Jocul nostru a fost în unele momente mult mai mult decât rezultatele.", author: "Claudiu Bumba", origin: "RO" },
  { text: "Ca Steaua să ajungă cea mai bună echipă din România, ar trebui să mă aibă pe mine, dar asta nu o să se întâmple niciodată.", author: "Alexandru Ioniță", origin: "RO" },
  { text: "Cel mai mult urăsc Steaua, nu știu de ce. Bine, adică eu știu de ce.", author: "Alexandru Ioniță", origin: "RO" },
  { text: "Dacă e să câștigăm e blat, pierdem, blat, egal, blat.", author: "Romario Benzar", origin: "RO" },
  { text: "Mi-am trăit traiul, mi-am halit mălaiul.", author: "Marin Barbu", origin: "RO" },
  { text: "Am un P mare pe spate și nu e de la Porumboiu, ci de la Prost.", author: "Adrian Porumboiu", origin: "RO" },
  { text: "Pentru moment, Mutu și Tamaș sunt excluși definitiv.", author: "Victor Pițurcă", origin: "RO" },
  { text: "Dacă nu dăm gol, e foarte greu să înscrii.", author: "Cosmin Vâtcă", origin: "RO" },
  { text: "Știți ce este în sufletul lui, probabil? Ce îmi dau eu seama... o amestecătură de idei.", author: "Cosmin Vâtcă", origin: "RO" },
  { text: "Am luat mingea, mi-am pus-o, am tras, am dat gol, ne-am bucurat, am plecat, ne-am îmbătat, am venit aici.", author: "Gabi Iancu", origin: "RO" },
  { text: "Este un trofeu important pentru noi. După cinci ani nu am mai câștigat niciun trofeu.", author: "Dan Nistor", origin: "RO" },
  { text: "Rapidul fără spectatori e ca o nuntă fără lăutari.", author: "Viorel Moldovan", origin: "RO" },
  { text: "Poate mai încolo, după puțin alcool.", author: "Aurelian Chițu", origin: "RO" },
  { text: "Intra primul la duș, intra apoi celălalt. Eram toți acolo în fundul gol.", author: "Nana Falemi", origin: "RO" },
  { text: "Nu m-am gândit niciodată ca să dau, să ies golgheter, eu îmi fac treaba să dau gol.", author: "George Țucudean", origin: "RO" },
  { text: "Ne pare rău pentru Bălă și pentru ceilalți care au ieșit mai sifonați de pe teren... Gnohere. Și cum îl cheamă... în fine, de la Viitorul, am uitat.", author: "Florin Niță", origin: "RO" },
  { text: "Avem echipe de tradiție care au început să apară.", author: "Răzvan Burleanu", origin: "RO" },
  { text: "Noi suntem rapidiști din tată-n fiu, în afară de fiul meu, care e stelist.", author: "Nicolae Văcăroiu", origin: "RO" },
  { text: "Ce face John Carew cu o minge, eu pot să fac cu o portocală.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Am mers la stânga, apoi la dreapta, apoi iar la stânga. El s-a dus să-și cumpere un hot-dog.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Nimic. Îl are deja pe Zlatan.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Când mă cumperi pe mine, cumperi un Ferrari. Guardiola l-a condus ca pe un Fiat.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Doar Dumnezeu știe.” „E greu să-l întrebăm.” „Vorbești cu el acum.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Dacă nu găsim un apartament, probabil cumpăr hotelul.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Zlatan nu dă probe.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Nu mă pot abține să nu râd când văd cât de perfect sunt.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Un Zlatan accidentat este o problemă destul de serioasă pentru orice echipă.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Am dormit în cadă. Acum rezist mult mai bine la vodcă.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Mi-e dor cel mai mult de la PSG? De ultimul meu salariu.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Am nevoie de dușmani noi. Cei vechi au devenit fanii mei.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Când îl văd pe Bill Gates nu simt puterea. Când îl văd pe Tony Montana, da.", author: "Zlatan Ibrahimović", origin: "INTL" },
  { text: "Când marchez nu sărbătoresc. Când poștașul livrează scrisorile, sărbătorește?", author: "Mario Balotelli", origin: "INTL" },
  { text: "Am cheltuit o grămadă de bani pe băutură, femei și mașini rapide. Restul i-am risipit.", author: "George Best", origin: "INTL" },
  { text: "În 1969 m-am lăsat de femei și alcool. Au fost cele mai proaste 20 de minute din viața mea.", author: "George Best", origin: "INTL" },
  { text: "Obișnuiam să miss destul de des... (Miss Canada, Miss Marea Britanie, Miss World).", author: "George Best", origin: "INTL" },
  { text: "Am încetat să mai beau. Dar numai când dorm.", author: "George Best", origin: "INTL" },
  { text: "Beckham nu poate șuta cu stângul, nu știe să dea cu capul și nu marchează prea mult. În rest, e în regulă.", author: "George Best", origin: "INTL" },
  { text: "I-am spus lui Gazza că are IQ-ul mai mic decât numărul de pe tricou. M-a întrebat ce este un IQ.", author: "George Best", origin: "INTL" },
  { text: "Am o casă lângă mare. Ca să ajung la plajă trebuia să trec pe lângă un bar. N-am văzut niciodată marea.", author: "George Best", origin: "INTL" },
  { text: "N-aș spune că sunt cel mai bun antrenor. Dar sunt în primul unu.", author: "Brian Clough", origin: "INTL" },
  { text: "Roma nu a fost construită într-o zi. Dar nici eu n-am lucrat la proiectul ăla.", author: "Brian Clough", origin: "INTL" },
  { text: "Discutăm 20 de minute și apoi hotărâm că eu am dreptate.", author: "Brian Clough", origin: "INTL" },
  { text: "Dacă nu deveneam fotbalist? Virgin.", author: "Peter Crouch", origin: "INTL" },
  { text: "N-am tatuaje, fiindcă niciun membru al corpului meu nu e suficient de lat.", author: "Peter Crouch", origin: "INTL" },
  { text: "Nu m-ar deranja să pierdem fiecare meci, atât timp cât câștigăm campionatul.", author: "Mark Viduka", origin: "INTL" },
  { text: "Când conduci cu 4-0, n-ar trebui niciodată să pierzi cu 7-1.", author: "Lawrie McMenemy", origin: "INTL" },
  { text: "Părinții mei au fost mereu alături de mine, încă de când aveam vreo șapte ani.", author: "David Beckham", origin: "INTL" },
  { text: "N-am fost niciodată atât de sigur. Vreau să devin antrenor. Sau manager. Nu sunt sigur care.", author: "Phil Neville", origin: "INTL" },
  { text: "Am participat la un turneu pentru un băiat rănit într-un accident. A trebuit să conduc ca un nebun ca să ajung.", author: "Ray Houghton", origin: "INTL" },
  { text: "Nu fac niciodată predicții și nici nu voi face vreodată.", author: "Paul Gascoigne", origin: "INTL" },
  { text: "Am luat opt examene la școală: zero la fiecare materie.", author: "Paul Gascoigne", origin: "INTL" },
  { text: "Sometimes maybe good, sometimes maybe shit.", author: "Gennaro Gattuso", origin: "INTL" },
  { text: "N-am reușit să mă acomodez în Italia. Era ca și cum aș fi locuit într-o țară străină.", author: "Ian Rush", origin: "INTL" },
  { text: "Aș vrea să joc la un club italian, cum ar fi Barcelona.", author: "Mark Draper", origin: "INTL" },
  { text: "Brazilienii erau sud-americani. Ucrainenii vor fi mai europeni.", author: "Phil Neville", origin: "INTL" },
  { text: "Din cele nouă cartonașe roșii, probabil că am meritat jumătate.", author: "Arsène Wenger", origin: "INTL" },
  { text: "Când un jucător ajunge la 30 de ani, la fel și corpul lui.", author: "Glenn Hoddle", origin: "INTL" },
  { text: "Foarte puțini știm cum e să trăiești într-un acvariu. În afară, evident, de cei dintre noi care sunt pești.", author: "Graham Taylor", origin: "INTL" },
  { text: "Nu comentez niciodată arbitrii și nu-mi voi încălca obiceiul pentru idiotul ăsta.", author: "Ron Atkinson", origin: "INTL" },
  { text: "Eram bolnav, nu mă antrenasem și aveam crampe. Dar nu sunt omul care să caute scuze.", author: "Peter Crouch", origin: "INTL" },
  { text: "Se pare că e vina mea și că Titanicul s-a scufundat.", author: "Clinton Morrison", origin: "INTL" },
  { text: "Dacă ești condus cu 0-0, nu există nimeni mai bun să te aducă la egalitate.", author: "Robbie Earle", origin: "INTL" },
  { text: "Germania e foarte greu de învins. Aveau 11 internaționali pe teren.", author: "Steve Lomas", origin: "INTL" },
  { text: "Vreau ca Brooklyn să fie botezat. Doar că încă nu știu în ce religie.", author: "David Beckham", origin: "INTL" },
  { text: "Pot juca în centru, în dreapta și, ocazional, pe partea stângă.", author: "David Beckham", origin: "INTL" },
  { text: "S-au enervat că mi-am dat tricoul jos? Mi-au văzut fizicul și au devenit geloși.", author: "Mario Balotelli", origin: "INTL" },
  { text: "Am niște dubii în privința a două certitudini.", author: "Giovanni Trapattoni", origin: "INTL" },
  { text: "În Irlanda plouă de două ori pe săptămână: de luni până miercuri și de joi până duminică.", author: "Giovanni Trapattoni", origin: "INTL" },
  { text: "Jucătorii sunt liberi să facă ceea ce le spun eu.", author: "Giovanni Trapattoni", origin: "INTL" },
  { text: "Este un gol pe care îl dedic în mod special tuturor.", author: "Totò Schillaci", origin: "INTL" },
  { text: "Am crescut într-un cartier privat: privat de lumină, de apă și de telefon.", author: "Diego Maradona", origin: "INTL" },
  { text: "Îmi cer mii de scuze englezilor. Dar aș face-o din nou de o mie de ori.", author: "Diego Maradona", origin: "INTL" },
  { text: "Voi deveni antrenor? Niciodată. N-aș putea suporta unul ca mine.", author: "Romário", origin: "INTL" },
  { text: "N-am nimic de declarat. Întrebări?", author: "Ray Hudson", origin: "INTL" },
  { text: "Nu alergam după femei. Ele se lăsau prinse.", author: "Adolfo Pedernera", origin: "INTL" },
  { text: "Este un precedent fără precedent.", author: "Clarke Carlisle", origin: "INTL" },
  { text: "Avea o eternitate să paseze mingea, dar i-a luat prea mult timp.", author: "Martin Tyler", origin: "INTL" },
  { text: "Există o singură posibilitate: victorie, egal sau înfrângere.", author: "Franz Beckenbauer", origin: "INTL" },
  { text: "Dacă mingea intra, era gol.", author: "Míchel", origin: "INTL" },
  { text: "Nu pot să vă spun țara... doar că este o echipă braziliană.", author: "Francisco Rojas", origin: "INTL" },
  { text: "Câți plămâni am? Unul, ca toată lumea, nu?", author: "Héctor Puebla", origin: "INTL" },
  { text: "Uneori, în fotbal, trebuie să marchezi goluri.", author: "Thierry Henry", origin: "INTL" },
  { text: "Ce aș vizita în Austria? Cangurii.", author: "Raúl Albiol", origin: "INTL" },
  { text: "Fotbalul este ca șahul, dar fără zaruri.", author: "Lukas Podolski", origin: "INTL" },
  { text: "Când eram mici, unora le plăcea baschetul, altora basketball-ul.", author: "Sergio Ramos", origin: "INTL" },
  { text: "Am pierdut pentru că n-am câștigat.", author: "Ronaldo Nazário", origin: "INTL" },
  { text: "Ca orice echipă africană, Jamaica va fi un adversar dificil.", author: "Edinson Cavani", origin: "INTL" },
  { text: "Pe măsură ce câștigi lucruri, te hamburghezești.", author: "Carlos Tévez", origin: "INTL" },
  { text: "Am văzut portarul ieșit și am dat peste el. A fost un gol de odontologie.", author: "Nelson Pedetti", origin: "INTL" },
  { text: "Am cerut să fiu transferat. Dar vreau să fie clar că nu vreau să plec.", author: "Stan Collymore", origin: "INTL" },
  { text: "M-am lovit la glezna stângă, dar ceva îmi spunea că era dreapta.", author: "Lee Hendrie", origin: "INTL" },
  { text: "Nu, nici una, nici alta, ci exact contrariul.", author: "Claudio Borghi", origin: "INTL" },
  { text: "Vreau să le mulțumesc părinților mei, în special tatălui și mamei mele.", author: "Alessandro Altobelli", origin: "INTL" },
  { text: "Sunt cât de fericit poate fi un om. Dar am fost și mai fericit.", author: "Ugo Ehiogu", origin: "INTL" },
  { text: "Nu i-am subestimat. Au fost mult mai buni decât credeam.", author: "Bobby Robson", origin: "INTL" },
  { text: "Am avut 99% din meci. Celelalte 3% ne-au costat partida.", author: "Ruud Gullit", origin: "INTL" },
  { text: "Am scris deja mai multe cărți decât am citit.", author: "Antonio Cassano", origin: "INTL" },
  { text: "Sporting a fost fondat în 1906. La anul va împlini o mie de ani.", author: "Marco Caneira", origin: "INTL" },
  { text: "Două ocazii, un gol. Asta numesc eu eficiență 100%.", author: "Roland Wohlfarth", origin: "INTL" },
  { text: "Brazilia va câștiga Euro 2008.", author: "Rafik Saïfi", origin: "INTL" },
  { text: "Nu există cale de mijloc: ori ești slab, ori ești bun. Noi am fost mediocri.", author: "Gary Lineker", origin: "INTL" },
  { text: "Trebuie să jucăm acasă așa cum jucăm la noi acasă.", author: "Jamel Abdoun", origin: "INTL" },
  { text: "Nu este nici locul, nici momentul potrivit să vorbim aici despre asta.", author: "Laurent Blanc", origin: "INTL" },
  { text: "Golurile sunt ca ketchupul: uneori nu ies, iar când ies, vin toate odată.", author: "Cristiano Ronaldo", origin: "INTL" },
  { text: "Am alergat până când ce am putut.", author: "Franck Ribéry", origin: "INTL" },
  { text: "Suntem niște jucători care mergem repede cu mingea.", author: "Franck Ribéry", origin: "INTL" },
  { text: "Acum va trebui să ne descurcăm cu fără Zizou.", author: "Franck Ribéry", origin: "INTL" },
  { text: "Sunt o persoană căreia îmi place mult să râd și să glumesc.", author: "Franck Ribéry", origin: "INTL" },
  { text: "La clinică unii se credeau Napoleon. Când spuneam că sunt Maradona, nu mă credea nimeni.", author: "Diego Maradona", origin: "INTL" },
  { text: "Dacă istoria se repetă, ar trebui să ne așteptăm să se întâmple din nou.", author: "Terry Venables", origin: "INTL" },
  { text: "Chiar dacă faultul nu e în careu, bineînțeles că e penalty.", author: "Xavier Gravelaine", origin: "INTL" },
  { text: "Bagă burta înăuntru, ești în ofsaid!", author: "Fotbal amator francez", origin: "INTL" },
  { text: "Ești mai slab când nu bei cu o seară înainte.", author: "Fotbal amator francez", origin: "INTL" },
  { text: "Dacă nu vă convine, luați voi fanionul!", author: "Fotbal amator francez", origin: "INTL" },
];
